name: Import DQT20 solution

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  import:
    name: Import to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    concurrency: import-dqt20-${{ github.event.inputs.environment }}

    steps:
    - run: |
        if [ "$ENVIRONMENT" == "build" ]; then
          echo "::error ::Cannot deploy to the build environment"
          exit 1
        fi
      env:
        ENVIRONMENT: ${{ github.event.inputs.environment }}

    - uses: actions/checkout@v2

    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: "Retrieve CRM secret"
      uses: DfE-Digital/keyvault-yaml-secret@v1.0.1
      id: CRM
      with:
        keyvault: ${{ secrets.KEYVAULT_NAME }}
        secret: CRM
        key: CRM_URL, CRM_APP_ID, CRM_APP_SECRET, CRM_TENANT_ID

    - name: "Retrieve PLUGIN-CONFIG secret"
      uses: DfE-Digital/keyvault-yaml-secret@v1.0.1
      id: PLUGIN_CONFIG
      with:
        keyvault: ${{ secrets.KEYVAULT_NAME }}
        secret: PLUGIN-CONFIG
        key: TRN_GENERATION

    - name: "Import solution & configure"
      run: |
        wget https://www.nuget.org/api/v2/package/Microsoft.PowerApps.CLI.Core.linux-x64 -P ~ \
          && unzip ~/Microsoft.PowerApps.CLI.Core.linux-x64 -d ~/pac \
          && chmod +x ~/pac/tools/pac \
          && export PATH=~/pac/tools:$PATH

        pac auth create --name $Environment --url $CrmUrl -id $CrmClientId -cs $CrmClientSecret -t $CrmTenantId

        pac solution pack --zipfile dqt20.zip --folder ./solutions/DQT20/ --packagetype Managed

        pac solution import --path dqt20.zip --async

        dotnet run --project ./SetPluginSecureConfigTool/SetPluginSecureConfigTool.csproj -c Release -- \
          --plugin-type Dqt.Dynamics.plugins.TrnGenerationPlugin --secure-config "$TrnGenerationPluginConfig"
      env:
        Environment: ${{ github.event.inputs.environment }}
        CrmUrl: ${{ steps.CRM.outputs.CRM_URL }}
        CrmClientId: ${{ steps.CRM.outputs.CRM_APP_ID }}
        CrmClientSecret: ${{ steps.CRM.outputs.CRM_APP_SECRET }}
        CrmTenantId: ${{ steps.CRM.outputs.CRM_TENANT_ID }}
        TrnGenerationPluginConfig: ${{ steps.PLUGIN_CONFIG.outputs.TRN_GENERATION }}
