name: Run script

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        default: 'build'
      args:
        description: 'Arguments to pass to DqtScripts app'
        required: true

jobs:
  run-script:
    name: Run script
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    concurrency: run-script-${{ github.event.inputs.environment }}

    steps:
    - uses: actions/checkout@v2

    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - id: crm
      uses: DfE-Digital/keyvault-yaml-secret@v1.0.1
      with:
        keyvault: ${{ secrets.KEYVAULT_NAME }}
        secret: CRM
        key: CRM_URL, CRM_APP_ID, CRM_APP_SECRET

    - id: storage
      uses: DfE-Digital/keyvault-yaml-secret@v1.0.1
      with:
        keyvault: ${{ secrets.KEYVAULT_NAME }}
        secret: DQT-SCRIPTS-STORAGE-SECRET
        key: BLOB_URI, CONTAINER_NAME, SAS_TOKEN

    - id: identity
      uses: DfE-Digital/keyvault-yaml-secret@v1.0.1
      with:
        keyvault: ${{ secrets.KEYVAULT_NAME }}
        secret: GET-AN-IDENTITY-SECRET
        key: CONNECTION_STRING

    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - run: dotnet run -c Release -- ${{ github.event.inputs.args }}
      env:
        CrmUrl: ${{ steps.crm.outputs.CRM_URL }}
        CrmClientId: ${{ steps.crm.outputs.CRM_APP_ID }}
        CrmClientSecret: ${{ steps.crm.outputs.CRM_APP_SECRET }}
        BlobUri: ${{ steps.storage.outputs.BLOB_URI }}
        BlobContainerName: ${{ steps.storage.outputs.CONTAINER_NAME }}
        BlobSasToken: ${{ steps.storage.outputs.SAS_TOKEN }}
        IdentityConnectionString: ${{ steps.identity.outputs.CONNECTION_STRING }}
      working-directory: DqtScripts/DqtScripts
